
TENSORFLOW USERS:
You must use the python3.6-anaconda/5.2.0 module to run TensorFlow.
See https://arc-ts.umich.edu/greatlakes/software/tensorflow for more
information.



The following have been reloaded with a version change:
  1) cuda/10.0.130 => cuda/10.1.105


Currently Loaded Modules:
  1) python3.7-anaconda/2019.07   2) cudnn/10.0-v7.6   3) cuda/10.1.105

 

mkdir: cannot create directory ‘results/5223252’: File exists
Test  1

Schema 1: Each client partially IID
--------------------------------------------------
percent data distributed IID:  80
number of classes for non-IID data:  2
data points per client (mean, std dev): ( 600 ,  10 )

cohort size:  10
number of local epochs:  20
local batch size:  10
learning rate:  0.2
target accuracy:  99 %
--------------------------------------------------
number of data points per client:
Traceback (most recent call last):
  File "tff_main.py", line 11, in <module>
    partitioner.go(int(sys.argv[1]))
  File "/home/apawlik/federated/each_client_partially_iid.py", line 160, in go
    print(num_data_per_client.astype(int))
AttributeError: 'list' object has no attribute 'astype'
